spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/escola
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

minio:
  url: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: students